### ISSUE TITLE
Debug mode `Promise.await_lwt` raising `Failure("Already in Eio context!")`

### ISSUE THREAD

**Issue by patricoferris** [ocaml-multicore/lwt_eio#29]
Hey, thanks for the library! 

It seems there's a case of `Eio,Eio` in debug mode that is causing a failure but I don't quite understand why.

```ocaml
let proc () =
  Lwt_process.pread_line ("", [| "whoami" |])

let () =
  Eio_main.run @@ fun env ->
  Lwt_eio.with_event_loop ~debug:true ~clock:env#clock @@ fun _ ->
  Eio.traceln "I am %s" (Lwt_eio.Promise.await_lwt (proc ()))
```

This program fails with:

```
+WARNING: Exception: Failure("Already in Eio context!")
+         No backtrace available.
Fatal error: exception Failure("Already in Eio context!")
whoami: write error: Broken pipe
```

Either setting `debug` to `false` or changing the program to have `Lwt_eio.run_lwt proc` (even with `~debug:true`) works. Am I doing something wrong? Should there be a `with_mode` inside the `Promise.await_lwt` rather than higher up in `run_lwt`? Sorry if I'm confused.

**Comment by talex5** [comment]
It's not a great error message, but the problem is you're running `proc` (a Lwt function) in Eio context. You want:
```ocaml
traceln "I am %s" (Lwt_eio.run_lwt proc)
```

(`OCAMLRUNPARAM=b` will get you a stack-trace)

**Comment by patricoferris** [comment]
Hmm, ok, when is the appropriate time to use `await_lwt` ? Just inside a call to `run_lwt` ?

**Comment by talex5** [comment]
`Promise.await_lwt` is useful if you're in Eio context and want to wait for some pre-existing Lwt promise. But if you need to run some Lwt code to create the promise then use `run_lwt` instead.

`run_lwt` is almost always what you want.

Technically, there's no problem running Lwt code in Eio context, but if we allow that then we can't tell when you're running Eio code from Lwt code, so it's easier to keep everything separated.

**Comment by patricoferris** [comment]
Awesome, thanks for clarifications :))
